---
title: "Churn Analysis - PowerCo"
author: "Fasih Atif"
date: "1/2/2021"
output: pdf_document
---
Define what is your (broad) research question! What you want to learn from the data or what you
want to use it?
(a) What is the main aim: prediction or causality?

```{r load_libraries, include=}
##########################################
#               Load libraries           #
##########################################
library(tidyverse)
library(data.table)
library(lubridate)
library(fastDummies)   # To create fummy variables
library(estimatr)
library(scales)        # To take logs of x and y variables
library(faraway)
library(caret)
library(car)           # To calculate VIF
library(corrplot)      # To draw correlation chart
library(outForest)
library(xgboost)
library(Ckmeans.1d.dp) # Required for xgb.ggplot.importance function in xgboost
library(randomForest)
library(Metrics)       # To calculate AUC
library(ggpubr)
```

```{r data_import, include=}
##########################################
#             Data Import                #
##########################################

# Import CustomerHistory.csv
urlCustomerHistory <- 'https://raw.githubusercontent.com/fasihatif/Data-Analysis-1-2-3/master/Data_Analysis_2/DA2_final_project/data/CustomerDetails.csv'
DfCustomerHistory <- read_csv(urlCustomerHistory)

# Import PricingHistory.csv
urlPricingHistory <- 'https://raw.githubusercontent.com/fasihatif/Data-Analysis-1-2-3/master/Data_Analysis_2/DA2_final_project/data/PricingHistory.csv'
DfPricingHistory <- read_csv(urlPricingHistory)

# Import ChurnOutput.csv
urlChurnOutput <- 'https://raw.githubusercontent.com/fasihatif/Data-Analysis-1-2-3/master/Data_Analysis_2/DA2_final_project/data/ChurnOutput.csv'
DfChurnOutput <- read_csv(urlChurnOutput)
```

```{r merge_data, include=}
##########################################
#         Understanding the Data         #
##########################################

df_draft %>% group_by(churn) %>%
  summarize(count = n())

# Number of rows in DfCustomerHistory
count(unique(DfCustomerHistory)) #16096

# Number of rows in DfChurnOutput
count(unique(DfChurnOutput)) #16096

# Merge dataframes by id column since equal and has unique ids. We create a df named df_draft where we do all the working for cleaning and feature engineering
df_draft <- merge(DfCustomerHistory,DfChurnOutput, by = 'id')

rm(DfChurnOutput,DfCustomerHistory)

# Get stats of each column
summary(df_draft) # add some analysis regarding consumption and forecasting

```

```{r data_cleaning, include=}
##########################################
#             Cleaning the Data          #
##########################################

# Number of missing values in each column
na_count <- sapply(df_draft, function(y) sum(length(which(is.na(y)))))
na_count <- data.frame(na_count)

# Number of missing values in percent in each column. 
# We will check which columns have missing values greater than 30% and drop them. We will also ensure that the columns to be dropped dont contain any important information inw hich case we wont drop them.
na_count$na_percent <- sapply(df_draft, function(y) round((sum(length(which(is.na(y))))/length(y))*100.00,2))

# Save the names of columns which have missing values less than 30%
col_30 <- na_count %>% filter(na_percent < 30)
col_30 <- rownames(col_30)

# Remove columns with NA values greater than 30%
df_draft <- df_draft %>% select(all_of(col_30))

# Fill in missing dates with median
## Replace NA values in 'date_end' column with median date
df_draft$date_end[is.na(df_draft$date_end)]<-median(df_draft$date_end,na.rm=TRUE)

##Replace NA values in 'date_renewal' column with median date
df_draft$date_renewal[is.na(df_draft$date_renewal)]<-median(df_draft$date_renewal,na.rm=TRUE)

## Replace NA values in 'date_modif_prod' column with median date
df_draft$date_modif_prod[is.na(df_draft$date_modif_prod)]<-median(df_draft$date_modif_prod,na.rm=TRUE)

## Replace NA values in channel sales column with 'null_channel'
df_draft$channel_sales[is.na(df_draft$channel_sales)] <- "null_channel"

# Convert 'has_gas' column from T/F to 1/0
df_draft <- df_draft %>% mutate('has_gas' =  as.numeric(has_gas))
```

```{r feature_engineering, include=}
##########################################
#            Feature Engineering         #
##########################################

# Create 'contract duration' column and divide by 365 to get yearly values
df_draft <- df_draft %>% mutate('contract_duration' =  as.integer((difftime(date_end,date_activ, unit = "days"))/(365.25/12)))

# Create reference date for calculations. We will take 1st Jan 2020 since it is given as the reference date
ref_date = ymd(20160101)

# No of years since contract went active
df_draft <- df_draft %>% mutate('months_active' =  as.integer((difftime(ref_date,date_activ, unit = "days"))/(365.25/12)))

# No of years left in contract
df_draft <- df_draft %>% mutate('months_end' =  as.integer((difftime(date_end,ref_date, unit = "days"))/(365.25/12)))

# No of years since last modification at reference date
df_draft <- df_draft %>% mutate('months_modif' =  as.integer((difftime(ref_date,date_modif_prod, unit = "days"))/(365.25/12)))

# Number of months since last renewal at reference date
df_draft <- df_draft %>% mutate('months_renewal' =  as.integer((difftime(ref_date,date_renewal, unit = "days"))/(365.25/12)))

# Remove columns with NA values greater than 30%
df <- df_draft %>% select(all_of(col_30), contract_duration,has_gas,months_active,months_end,months_modif,months_renewal)
df <- df %>% select(-c(date_activ,date_end,date_modif_prod,date_renewal, date_renewal,forecast_cons_year, origin_up))

# Dummy Variable creation for channel_sales and has_gas
## How many dummy columns to make?
# df_backup <- df

df %>% 
  group_by(channel_sales) %>%
  summarize(channel_count = n()) # 8 unique channels so we will make 8 dummy columns

## Create dummy variables using the fastdummies library
df <- df %>% dummy_cols(select_columns = c("channel_sales","has_gas"), remove_selected_columns = TRUE)

## Updating column names of dummy variables for easier understanding
df <- df %>% 
  rename(
    "channel_foos" = channel_sales_foosdfpfkusacimwkcsosbicdxkicaua,
    "channel_usil" = channel_sales_usilxuppasemubllopkaafesmlibmsdf,
    "channel_lmke" = channel_sales_lmkebamcaaclubfxadlmueccxoimlema,
    "channel_ewpa" = channel_sales_ewpakwlliwisiwduibdlfmalxowmwpci,
    "channel_epum" = channel_sales_epumfxlbckeskwekxbiuasklxalciiuu,
    "channel_sddi" = channel_sales_sddiedcslfslkckwlfkdpoeeailfpeds,
    "channel_fixd" = channel_sales_fixdbufsefwooaasfcxdxadsiekoceaa,
    "channel_null" = channel_sales_null_channel
  )

## Remove one of the dummy columns to cater for multicollinearity. We will remove 'channel_null' and 'has_gas_0'
df <- subset(df,select = -c(channel_null,has_gas_0))

```

```{r}
```

```{r}

```

\Newpage 

APPENDIX

**Figure:  - Churn Rate**
```{r, echo = FALSE, warning= FALSE,message= FALSE, fig.width=8,fig.height=4}
print(churn_rate_barchart)
```

```{r months_active_end, echo=FALSE, fig.height=4, fig.width=8, message=FALSE, warning=FALSE}
ggarrange1 <- ggarrange(months_active_barchart,months_end_barchart,months_renewal_barchart,months_modif_barchart,
          nrow = 2, ncol = 2,
          common.legend = TRUE,
          labels = c("Months Active", "Months End", "Months Renewal", "Months_modif"),
          vjust = c(-0.5,-0.5,0.4,0.4),
          hjust = c(-1.8,-2.4,-1.5,-2.0),
          font.label = list(size = 10))

annotate_figure(ggarrange1,
                bottom = text_grob("No of Months", color = "black",
                                   hjust = 4, x = 1, size = 11, face = "bold"),
                left = text_grob("No of Companies", color = "black", rot = 90, face = "bold",size = 11))
```

```{r consumption_eda, echo = FALSE, warning = FALSE, message = FALSE}
##### CONSUMPTION VARIABLES EXPLORATORY ANALYSIS #####
annotate_figure(consumption_eda,
                bottom = text_grob("Consumption", color = "black",
                                   hjust = 5, x = 1, size = 11, face = "bold"),
                left = text_grob("No of Companies", color = "black", rot = 90, face = "bold",size = 11))


```

```{r forecast_eda, echo=FALSE, message=FALSE, warning=FALSE}
annotate_figure(forecast_eda,
                bottom = text_grob("Dollars ($)", color = "black",
                                   hjust = 5, x = 1, size = 11, face = "bold"),
                left = text_grob("No of Companies", color = "black", rot = 90, face = "bold",size = 11))
```

```{r margin_eda, echo = FALSE, message=FALSE, warning=FALSE}
annotate_figure(margin_eda,
                bottom = text_grob("Dollars ($)", color = "black",
                                   hjust = 4.8, x = 1, size = 11, face = "bold"),
                left = text_grob("No of Companies", color = "black", rot = 90, face = "bold",size = 11))
```

```{r other_eda, echo = FALSE, message=FALSE, warning=FALSE}
annotate_figure(other_eda,
                bottom = text_grob("Value", color = "black",
                                   hjust = 8.8, x = 1, size = 11, face = "bold"),
                left = text_grob("No of Companies", color = "black", rot = 90, face = "bold",size = 11))
```



